### ISSUE TITLE
EFI worked on which macos version?

### ISSUE THREAD

**Issue by lizilong1993** [YumNumm/surface-laptop-2-OpenCore-EFI#1]
help

**Comment by lizilong1993** [comment]
Thankyou for the EFI，I had try mojave10.14.4 and it worked well 。But my keyboard doesnt work, Can you give me some suggestions? Thank u very much.

**Comment by YumNumm** [comment]
Hi. The keyboard of surface laptop 2 is not as normal as other PCs. (idk but if someone create patch for this, it can be worked. So at this print, we can't use build-in keyboard.  )
I had to use USB keyboard. I'm so sorry to help you. 

(I'm Japanese student so my English may wrong. Please forgive me. )
